In [1]:
import numpy as np

In [63]:
t = [[1,2,3], [4,5,6]]
tt = np.array(np.meshgrid(*t))

In [69]:
tt.reshape(2, 9)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [53]:
independent_variable_range = [[1,2], [2,3], [4,5], [5,6]]
a = np.array([np.linspace(v_range[0], v_range[1], 4) for v_range in independent_variable_range])


In [56]:
def fun1(x, y, z, t):
    return x ** 2 + y

res = fun1(*a)
res = res.reshape(1, -1)
res_t = res.T
res - res_t

array([[ 0.        ,  1.11111111,  2.44444444,  4.        ],
       [-1.11111111,  0.        ,  1.33333333,  2.88888889],
       [-2.44444444, -1.33333333,  0.        ,  1.55555556],
       [-4.        , -2.88888889, -1.55555556,  0.        ]])

In [40]:
ant_indices = np.arange(10)
np.random.choice(ant_indices)

1

In [93]:
np.random.uniform(*[[-3, -2.8], [-5, -4.8]])

array([-3.85968806, -3.79877508])